title: Biofilter Manual
description: A dynamic documentation website for LOKI and Biofilter
theme: just-the-docs

url: https://ritchielab.github.io/biofilter-manual

logo: "/assets/images/ritchie-lab-logo-2022-v3-vertical-transparent.png"